// Mocks generated by Mockito 5.4.6 from annotations
// in flowery_driver/test/modules/auth/data/repositories/send_application_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dio/dio.dart' as _i5;
import 'package:flowery_driver/modules/auth/data/datasources/apply_data_source.dart'
    as _i3;
import 'package:flowery_driver/modules/auth/data/models/apply_response.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeApplyResponse_0 extends _i1.SmartFake implements _i2.ApplyResponse {
  _FakeApplyResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ApplyDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockApplyDataSource extends _i1.Mock implements _i3.ApplyDataSource {
  MockApplyDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.ApplyResponse> apply({
    required String? firstName,
    required String? lastName,
    required String? email,
    required String? phone,
    required String? password,
    required String? gender,
    required String? country,
    required String? vehicleType,
    required String? vehicleNumber,
    required _i5.MultipartFile? vehicleLicense,
    required String? nid,
    required _i5.MultipartFile? nidImg,
    required String? rePassword,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#apply, [], {
              #firstName: firstName,
              #lastName: lastName,
              #email: email,
              #phone: phone,
              #password: password,
              #gender: gender,
              #country: country,
              #vehicleType: vehicleType,
              #vehicleNumber: vehicleNumber,
              #vehicleLicense: vehicleLicense,
              #nid: nid,
              #nidImg: nidImg,
              #rePassword: rePassword,
            }),
            returnValue: _i4.Future<_i2.ApplyResponse>.value(
              _FakeApplyResponse_0(
                this,
                Invocation.method(#apply, [], {
                  #firstName: firstName,
                  #lastName: lastName,
                  #email: email,
                  #phone: phone,
                  #password: password,
                  #gender: gender,
                  #country: country,
                  #vehicleType: vehicleType,
                  #vehicleNumber: vehicleNumber,
                  #vehicleLicense: vehicleLicense,
                  #nid: nid,
                  #nidImg: nidImg,
                  #rePassword: rePassword,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.ApplyResponse>);
}
